name: WakaTime
on:
  schedule:
    - cron: 0 */12 * * *
  workflow_dispatch:
jobs: 
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_WAKA_TOKEN }}
          COMMIT_MESSAGE: "Update README.md with WakaTime Stats"
          SHOW_UPDATED_DATE: "True"
          UPDATED_DATE_FORMAT: "%Y-%m-%d @%H:%M:%S"
          SHOW_COMMIT: True
          SHOW_DAYS_OF_WEEK: True
          SHOW_LANGUAGE_PER_REPO: True
          SHOW_TIMEZONE: False
          SHOW_LANGUAGE: True
          SHOW_PROJECTS: True
          SHOW_OS: True
          SHOW_EDITORS: True
          SHOW_LINES_OF_CODE: True
          SHOW_TOTAL_CODE_TIME: True
          SHOW_PROFILE_VIEWS: True
          SHOW_SHORT_INFO: True
          SHOW_LOC_CHART: True
